# Generated by Django 6.0.3 on 2026-04-28 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Cryptocurrency'), ('forex', 'Forex'), ('etf', 'ETF'), ('commodity', 'Commodity')], max_length=20)),
                ('exchange', models.CharField(max_length=50)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50)),
                ('content', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('avg_buy_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='investments.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('close', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.BigIntegerField()),
                ('interval', models.CharField(choices=[('1m', '1 Minute'), ('1h', '1 Hour'), ('1d', '1 Day'), ('1w', '1 Week')], max_length=5)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('macd_signal', models.FloatField(blank=True, null=True)),
                ('macd_hist', models.FloatField(blank=True, null=True)),
                ('ema_20', models.FloatField(blank=True, null=True)),
                ('ema_50', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='investments.asset')),
            ],
            options={
                'verbose_name_plural': 'Price histories',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['asset', 'interval', 'recorded_at'], name='investments_asset_i_6b2899_idx')],
            },
        ),
    ]
