# Generated by Django 6.0.1 on 2026-05-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
