# Generated by Django 6.0.3 on 2026-05-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_holding_notes_holding_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly passive income (e.g. rent)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Cryptocurrency'), ('forex', 'Forex'), ('etf', 'ETF'), ('commodity', 'Commodity'), ('nft', 'NFT'), ('bond', 'Bond'), ('mutual_fund', 'Mutual Fund'), ('real_estate', 'Real Estate')], max_length=20),
        ),
    ]
