"""
Shared intent training phrases for PyTorch (BoW) and sklearn (TF-IDF) classifiers.
Edit here, then re-run train_bot.py and train_sklearn_intent.py.
"""

FINORA_INTENTS = {
    "greeting": [
        "hello",
        "hi",
        "hey",
        "good morning",
        "good evening",
        "what is up",
        "help me",
        "hey bot",
        "hello finora",
        "yo",
        "greetings",
        "howdy",
        "can you help me",
        "i need assistance",
        "are you there",
        "hi there",
        "hello ai",
        "what's up",
        "good afternoon",
        "who are you",
        "what can you do",
        "start",
        "menu",
    ],
    "check_budget": [
        "what is my budget",
        "how much budget do I have left",
        "budget status",
        "am I broke",
        "how much can I spend",
        "spend limit",
        "can I afford this",
        "whats left in my budget",
        "show me my budget",
        "do i have budget left",
        "monthly budget",
        "did i overspend",
        "budget limit",
        "what is my spending limit",
        "tell me my budget",
        "how much room left in budget",
        "am i under budget",
        "budget left this month",
        "remaining budget",
        "did i blow my budget",
    ],
    "check_balance": [
        "what is my balance",
        "show my money",
        "how much cash do I have",
        "account balance",
        "my net worth",
        "total balance",
        "how rich am i",
        "how much do i have in total",
        "current balance",
        "show me my net worth",
        "total remaining money",
        "my checking balance",
        "how much money do i have",
        "what is my net cashflow",
        "do i have money left",
        "liquid cash",
    ],
    "check_spending": [
        "how much have I spent",
        "what are my expenses",
        "show my spending",
        "where did my money go",
        "expenses this month",
        "total spent this month",
        "how much did I spend",
        "my expenditure",
        "show me expenses",
        "recent expenses",
        "spending summary",
        "spent so far",
        "breakdown of spending",
        "category spending",
        "biggest expenses",
        "what did i buy",
        "track my spending",
        "how much on food",
        "monthly burn rate",
    ],
    "check_goals": [
        "what are my goals",
        "show my financial goals",
        "how far along am I",
        "target savings",
        "goal progress",
        "did i reach my goals",
        "how are my goals doing",
        "savings goals",
        "my active goals",
        "update on goals",
        "list my goals",
        "when will i finish my goal",
        "how long to reach my savings target",
        "goal timeline",
        "emergency fund progress",
    ],
    "check_portfolio": [
        "my portfolio",
        "how are my investments doing",
        "show my stocks",
        "my holdings",
        "investment performance",
        "how is my crypto",
        "my etf positions",
        "list my investments",
        "stock portfolio summary",
        "unrealized gains",
        "how much did i invest",
        "current value of my portfolio",
        "my mutual funds",
        "real estate holdings in finora",
    ],
    "investing_advice": [
        "how to invest",
        "give me investing advice",
        "stocks",
        "bonds",
        "what should I invest in",
        "grow my money",
        "passive income",
        "how to buy stocks",
        "best investments",
        "index funds",
        "etf",
        "investing strategies",
        "how to build wealth",
        "start investing",
        "dollar cost averaging",
        "asset allocation",
        "diversify my portfolio",
        "long term investing tips",
    ],
    "debt_advice": [
        "how to pay off debt",
        "debt snowball",
        "credit card debt",
        "loans",
        "avalanche method",
        "getting out of debt",
        "eliminate debt",
        "pay down loans",
        "reduce my debt",
        "student loans",
        "how to get debt free",
        "high interest debt",
        "minimum payments killing me",
    ],
    "market_status": [
        "how is the stock market",
        "what are the stocks doing",
        "market update",
        "live market",
        "is the market up",
        "spy price",
        "apple stock",
        "bitcoin price",
        "live stock data",
        "current market trends",
        "what's green today",
        "is the market crashing",
        "nasdaq today",
        "s and p today",
        "market sentiment",
    ],
    "improve_savings": [
        "how do i save more",
        "i have no money",
        "teach me how to save",
        "i want to stop spending",
        "reduce my expenses",
        "how to budget better",
        "frugal tips",
        "savings tips",
        "how to build an emergency fund",
        "ways to cut back",
        "save money",
        "spend less",
        "lower bills",
        "cut subscriptions",
    ],
    "tax_advice": [
        "how to file taxes",
        "tax deductions",
        "lower my taxes",
        "tax brackets",
        "what are write offs",
        "how do taxes work",
        "tax planning",
        "minimize taxes",
        "capital gains tax",
        "tax returns",
        "w4 withholding",
        "estimated taxes",
    ],
    "crypto_advice": [
        "should i buy bitcoin",
        "what is ethereum",
        "crypto investing",
        "cryptocurrency",
        "buy crypto",
        "blockchain",
        "is crypto safe",
        "dogecoin",
        "solana",
        "altcoins",
        "self custody wallet",
    ],
    "retirement_advice": [
        "how to retire early",
        "what is a 401k",
        "roth ira",
        "traditional ira",
        "retirement planning",
        "how much do i need to retire",
        "fire movement",
        "pension",
        "employer match",
        "catch up contributions",
    ],
    "real_estate": [
        "buy a house",
        "mortgage rates",
        "real estate investing",
        "should i rent or buy",
        "down payment",
        "buying property",
        "housing market",
        "rental property",
        "refinance mortgage",
        "hoa fees",
    ],
    "unknown": [
        "asdfgh",
        "qwerty",
        "this makes no sense",
        "afjaslfkj",
        "unknown word",
        "random gibberish phrase",
        "blah blah unrelated",
    ],
}
