# Generated by Django 6.0.1 on 2026-05-10 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('it', 'IT'), ('finance', 'Finance'), ('engineering', 'Engineering'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('government', 'Government'), ('other', 'Other')], max_length=20)),
                ('avg_salary_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('median_salary_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('p25_salary_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('p75_salary_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_of_living_index', models.FloatField()),
                ('data_year', models.IntegerField(default=2025)),
                ('source', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('it', 'IT'), ('finance', 'Finance'), ('engineering', 'Engineering'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('government', 'Government'), ('other', 'Other')], max_length=20)),
                ('job_title', models.CharField(max_length=200)),
                ('experience_yrs', models.IntegerField()),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salary_currency', models.CharField(max_length=3)),
                ('salary_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalarySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salary_pkr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('global_pctile', models.FloatField()),
                ('country_pctile', models.FloatField()),
                ('industry_pctile', models.FloatField()),
                ('benchmarks', models.JSONField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
