# Generated by Django 6.0.1 on 2026-05-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_reality', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.DeleteModel(
            name='GlobalBenchmark',
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='experience_yrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='salary_currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
        migrations.AlterField(
            model_name='salarysnapshot',
            name='benchmarks',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='salarysnapshot',
            name='country_pctile',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salarysnapshot',
            name='global_pctile',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salarysnapshot',
            name='industry_pctile',
            field=models.FloatField(default=0),
        ),
    ]
