# Generated by Django 6.0.1 on 2026-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_reality', '0002_delete_exchangerate_delete_globalbenchmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryprofile',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='dependents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='salary_frequency',
            field=models.CharField(default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='industry',
            field=models.CharField(choices=[('it', 'IT'), ('finance', 'Finance'), ('engineering', 'Engineering'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('government', 'Government'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
